supporter_system/config/routes.rb
Rails.application.routes.draw do

  root 'requests#index'
  resources :requests

  post "/requests/status/:id" => "requests#update_status", as: 'update_status'

end

supporter_system/app/models/request.rb
class Request < ActiveRecord::Base

  self.per_page = 7

  validates :name, presence:true
  validates :department, presence:true
  validates :message, presence: true, uniqueness: {scope: :name}

  def self.search(str)
    where("name ILIKE ? OR email ILIKE ? OR department ILIKE ? OR message ILIKE ?", "%#{str}%", "%#{str}%","%#{str}%","%#{str}%")
  end

end

supporter_system/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

supporter_system/app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_action :find_request, only: [:show, :destroy, :edit, :update, :update_status]

  def index
    # @requests = Request.all
    #
    # byebug
    if params[:search]
      @requests = Request.search(params[:search]).paginate(:page=>params[:page]).order("status DESC")
    else
      @requests = Request.all.paginate(:page=>params[:page]).order("status DESC")
    end
  end

  def new
    @request = Request.new
  end

  def create
    @request = Request.new request_params
    @request.status = "undone"

    # byebug
    if   @request.save
      redirect_to request_path(@request), notice: "post created successfully"
    else
      flash[:alert] = "Error creating this request!"
      # render :text => params.inspect
      render :new
    end
  end

  def show

  end

  def edit
  end

  def update
    @request.update request_params
    redirect_to request_path(@request), notice: "Request updated successfully"
  end

  def destroy
    @request.destroy
    redirect_to requests_path, notice: "Request deleted successfully"
  end

  def update_status
    # byebug
    if @request.status.downcase == "undone"
      @request.update status: "Done!"
    else
      @request.update status: "undone"
    end
    redirect_to requests_path, notice: "Status for request #{@request.id} updated successfully"
  end

  private

  def find_request
    @request = Request.find params[:id]
  end

  def request_params
    params.require(:request).permit([:name,:email, :department, :message, :status])
  end

end

supporter_system/app/helpers/application_helper.rb
module ApplicationHelper
end

supporter_system/app/helpers/requests_helper.rb
module RequestsHelper
end

supporter_system/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<style>
.banner{
  width:60%;
  margin-left: 20%;
}
body{
  margin: 5% 10% 0 10%;
}

table, tr, td{
  border: 1px solid #ddd;
}

tr:nth-child(odd) {
  background: rgb(233, 219, 233);
}

tr:nth-child(even) {
  background: beige;
}

.notice{
  color:red;
  text-align: center;
}

</style>
<title>SupporterSystem</title>
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<%= csrf_meta_tags %>
</head>
<body>

  <div class="navbar">
    <%= link_to "HOME", root_path %> |
    <%= link_to "NEW REQUEST", new_request_path%>
  </div>

  <img class="banner" src="http://facilities.nmsu.edu/wp-content/uploads/sites/57/2013/09/btn_service1.gif" />
  <div class="notice"> <%= notice || alert %></div>
  <%= yield %>

</body>
</html>

supporter_system/app/views/requests/_form.html.erb
<ul>
  <% @request.errors.full_messages.each do |m|  %>
  <li class="notice"><%= m %></li>
  <% end %>
</ul>


<%= form_for @request do |f| %>
<%# f is form object %>
<div>
  <%= f.label :name %>
  <%= f.text_field :name %>
</div>

<div>
  <%= f.label :email %>
  <%= f.text_field :email %>
</div>

<div>
  <%= f.label :department %>
  
  <%= f.radio_button :department, "Sales" %>
  <%= f.label :department_sales, "Sales" %>

  <%= f.radio_button :department, "Marketing" %>
  <%= f.label :department_marketing, "Marketing" %>

  <%= f.radio_button :department, "Technical" %>
  <%= f.label :department_technical, "Technical" %>
</div>

<div>
  <%= f.label :message %>
  <%= f.text_area :message %>
</div>

<div>
  <%= f.submit %>
</div>

<% end %>

supporter_system/app/views/requests/edit.html.erb
<h1 class="title">Edit Support Request</h1>

<%= render "form" %>

supporter_system/app/views/requests/index.html.erb
<div class="search_bar">
  <%= form_tag(requests_path, :method => "get", id: "search-form") do %>
  <%= text_field_tag :search, params[:search], placeholder: "keyword" %>
  <%= submit_tag "Search", :name => nil , class: "button" %>
  <% end %>
</div>
<br>
<!-- <div class="request-body">

<%= table_for @requests do -%>
<% columns :name,
:email,
:department,
:message,
:status %>
<% end %>

<%= will_paginate %>

</div> -->
<div class="request-body">
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Department</th>
        <th>Message</th>
        <th>Action</th>
        <th>Status</th>

      </tr>
    </thead>
    <tbody>
      <% @requests.each do |r| %>
      <tr>
        <td><%=r.name%></td>
        <td><%=r.email%></td>
        <td><%=r.department%></td>
        <td><%=r.message%></td>
        <td> <%= link_to "Delete", r, method: :delete, data: {confirm: "Are you sure?"} %> | <%= link_to "Edit", edit_request_path(r) %> </td>
        <td><%=button_to r.status, update_status_path(r)%></td>

      </tr>
      <% end %>
    </tbody>
  </table>
  <%= will_paginate %>
</div>

supporter_system/app/views/requests/new.html.erb
<h1 class="title">New Support Request</h1>

<%= render "form" %>

supporter_system/app/views/requests/show.html.erb
<p class="request-content"><%= "Requested by: #{raw@request.name}" %></p>
<p class="request-content"><%= "Email: #{raw@request.email}" %></p>
<p class="request-content"><%= "Department: #{raw@request.department}" %></p>
<p class="request-content"><%= "Request detail: #{raw@request.message}" %></p>
<p class="date"><%="CREATED AT: #{@request.created_at}" %></p>

<div>
  <p><%= link_to "Delete", @request, method: :delete, data: {confirm: "Are you sure?"} %> |
    <%= link_to "Edit", edit_request_path %> </p>
  </div>